# Site settings
title: Log Blog
email:
description: Personal Blog
baseurl:
url:
twitter_username: hapidznur
github_username:  hapidznur
theme: jekyll-theme-architect

# Build settings
markdown: kramdown
permalink: pretty
include: ['_pages']
