title:            NedNight
tagline:          'A Jar of Journay'
description:      'A nganu Blog'
url:              http://hapidznur.github.io
baseurl: 
url: http://hapidznur.github.io
logo: ''

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: hapidznur
  description: A noob <strong>developer and researcher</strong>.
  gravatar: 424e78eb856f7e669834f0d8ba74e363 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/hapidznur
    github:    https://github.com/hapidznur
    # facebook:  <hide>
    twitter:   https://twitter.com/hapidznur
    # weibo:     <hide>
    email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'http://hapidznur.github.io/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /assets/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-129747684-1' # leave blank if you don't want google analytics
disqus_short_name: 'disqus_KG3qpT6sNK' # leave blank if you don't want disqus
